### ISSUE TITLE
Fonts on Cloudflare Retuns 404

### ISSUE THREAD

**Issue by maxswjeon** [janmarthedal/gatsby-remark-mathjax-ssr#1]
In file mathjax.css, it requests its font file from [Cloudflare CDN Site](https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.8/fonts/HTML-CSS/TeX/woff/MathJax_Vector-Regular.woff). However, the site returns 404.  
If we request the file version [2.7.7](https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/fonts/HTML-CSS/TeX/woff/MathJax_Vector-Regular.woff), it works well.

**Comment by janmarthedal** [comment]
Thank you for creating this issue, it definitely needed fixing.

It has been fixed by commit https://github.com/janmarthedal/gatsby-remark-mathjax-ssr/commit/aee691573e37bb19cd268750b75a9d0ba2a82955 by setting a specific `fontURL` in the script that creates the `mathjax.css` file. It now uses *jsDelivr* instead of *cdnjs* since the latter didn't have the MathJax 2.7.8 font files (as you noted).
